### ISSUE TITLE
正面不写note时会导致导出谱面无法读取

### ISSUE THREAD

**Issue by EDTA-gif** [NagaseIori/DyNode#104]
在正面不写note时导出的xml文件是这样的形式
```
<m_notes>
	<m_notes>
		<CMapNoteAsset></CMapNoteAsset>
	</m_notes>
</m_notes>
<m_notesLeft>
……
```
导入炸药后会报错Load XML Failed: Object reference not set to an instance of an object
实测手动删除空CMapNoteAsset项即可正常读取
```
<m_notes>
	<m_notes>
	</m_notes>
</m_notes>
<m_notesLeft>
……
```

**Comment by NagaseIori** [comment]
fixed https://github.com/NagaseIori/DyNode/commit/c07bdb466e8b861fe36728967d06a6a672643ee3
