### ISSUE TITLE
我觉得应该加一个调节曲子音量大小的功能

### ISSUE THREAD

**Issue by AXIS5hacker** [NagaseIori/DyNode#105]
有的时候可能选的曲子音量过大，会对听觉造成损伤，这时候应该有一个可以调节曲目音量的功能来减弱音量，这样才能在不损伤听力的情况下写谱

**Comment by NagaseIori** [comment]
是的，目前DyNode还没有添加调节音量的功能，如果目前音量过大我们建议可以暂时通过Windows提供的**音量混合器（音量合成器）**单独调节DyNode应用程序的音量或将整体系统的音量调低。你也可以直接对原音频文件进行音量的处理。

关于DyNode的音量调节功能实际上已经制作完毕，但还需要最后的调整，因此没有在最新的版本里实装。

如果不出意外的话，下一个版本应该就会实装音量调节与右键菜单等功能。目前还请耐心等待 :)。
