### ISSUE TITLE
bar line 样式增加

### ISSUE THREAD

**Issue by Alexair059** [NagaseIori/DyNode#106]
### 正面 bar line 左右两端未延伸到左右侧”最底端“

总觉得视觉上有一点点奇怪，在放边界note时会难受（

### 大小节的颜色配比会在下列情况造成不便

- 侧面放note想寻找正面对应节拍线时不好找
- 白 -> 红 ->蓝 -> 红 ->白的配色与浅蓝容易混淆

### 具体展示

![屏幕截图 2023-05-27 142751](https://github.com/NagaseIori/DyNode/assets/69112237/44c228b2-452e-4aa0-8dc7-bb4e0d5a4a9b)

### 希望的东西

- 增加 bar line 样式，我认为dynamaker的 bar line 更加简洁，可以借鉴
- 或者简化 bar line 的配色，避免与侧面对应的浅蓝 bar 混淆

**Comment by NagaseIori** [comment]
（侧面的拍线是可以启用的，可能目前版本启用侧面的拍线会更好帮助你去找到对应的颜色）

之后我们会添加简化拍线颜色与延长拍线长度的选项

**Comment by NagaseIori** [comment]
我们添加了三种拍线样式：经典、等长与单色。预计使用<kbd>J</kbd>进行样式的切换。下面是依照顺序的预览：
![SH6JFV2PV](https://github.com/NagaseIori/DyNode/assets/31349569/d02320eb-6ce8-401c-b723-54f378d66396)
![8KJ1UQCF6](https://github.com/NagaseIori/DyNode/assets/31349569/b072a036-e3b4-4900-b09c-f55252ed5fbb)
![N2LSW9Q8I](https://github.com/NagaseIori/DyNode/assets/31349569/6ecb5baf-b394-4668-b90b-a4671b4178fe)

如果你认为该效果还有进一步的改善空间，请进一步反馈 :)

**Comment by Alexair059** [comment]
非常感谢！谢谢你的辛苦付出 ❤️
