### ISSUE TITLE
全局音符属性修改

### ISSUE THREAD

**Issue by kongbai141** [NagaseIori/DyNode#44]

**Comment by NagaseIori** [comment]
你说的谱面倍速是指音乐倍速还是下落速度？
音乐倍速可以用WS调整（会影响谱面整体的播放速度），下落速度可以用QE调整

如果这两个都不是你需要的倍速，你可能需要更加详细地描述一下什么是谱面倍速及其功能

**Comment by kongbai141** [comment]
就是把铺面以倍速导出
