### ISSUE TITLE
音符属性恒定显示

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#58]
可以的话在note上加上combo数，如果是多压则显示多个，方便看到异面同时落的note，可以的话设个快捷键
作者辛苦了，人在抄谱，把一些我能想到的功能给你提一下

**Comment by NagaseIori** [comment]
可以考虑添加此功能
也有在考虑增加另一种编辑模式，正侧面多押在这种模式下应该会更好读

**Comment by NagaseIori** [comment]
https://github.com/NagaseIori/DyNode/commit/7c70a42372a9d89d4d37faf5afba755dc3e3d638
