### ISSUE TITLE
功能意见参考（系列）1

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#60]
1.
![参考主题](https://user-images.githubusercontent.com/68184937/198921459-22e32799-fe5e-4ab4-b763-3eaa8bebe8a4.png)
这个算主题优化吧，与前一个建议的图片对比，毕竟是编辑器，官方这边hold的边（？）没有原作及这个编辑器这样粗，边弄得很细可以确保判定时看的清楚些，不至于每次都要回到编辑器模式点开note看判定时间，毕竟编辑模式不需要像预览模式一样看播出效果
2.
如前面所说，其实不仅仅是边的事，还有特效，这边并没有看到特效大小的设置，piano主题也只是把特效变淡了，但这边不建议快捷键（太多了），建议如6条
3.
想法来自re:phiedit，既然支持特殊的节奏拍号，可不可以选择用1/x的方式，对x进行逐步增加，当然因为大部分歌曲还是常规的拍号，所以现在这个拍号选择方案也可以保留，可一个就是两种方案依旧用快捷键很麻烦，建议依旧如6条，还有一个是对于节拍线的显示并不友好。。。还请作者大大加油，这个意见想着是能更好包容更多（令谱师吐血的）歌曲
4.
关于判定显示，比起特效，个人认为有一个更好的方案，那就是对应位置显示对立颜色相等长度的较粗的线（类比于deemo），比如Note (Tap)判定时消失的那一帧里显示对应位置相等长度的对立色（白色），Chain (Slide)则是绿色（红色的对立色），对于hold则是首判蓝色，中间用紫色，结尾蓝色淡出，至于所有note淡出时间，建议是尽可能短但肉眼可察觉到，时间倒退时对于刚判定的note要考虑是否显示淡出动画，当然这个有些画蛇添足，算是视觉优化，更方便看到判定时间罢了
5.
对于节拍线和对应时间的操作，来回总是用ad键进行调整来达到对应节拍线接近判定线的目的，这个可以考虑一下是否固定一下节拍线在判定线前，这个还是有些画蛇添足，仅作参考吧
6.
由于制谱器功能的增加，哪怕以上功能都不添加，制谱器也不能仅靠快捷键实现一系列功能，个人认为一定要有个设置选项，可以考虑工具栏（打开与否可以放在设置里），由于对于各种功能的多种编辑方式的增加，可以在设置里选择需要的对应功能编辑模式，这里建议为以后的扩展和优化，选择用列表或字典的方式进行编写（说白了编辑模式的选择在设置里以列表方式展开），用bool值不太好，诸如上面种种功能放在设置里最好

正值高三学业，至少这一年我真的没法帮忙（况且编程只是入个皮毛），以上是我在使用编辑器时的一点拙见，后续还会提意见，若有考虑不周或冒犯，还请指正并见谅QAQ

**Comment by NagaseIori** [comment]
我个人还是希望建议能够分issue列出..
1. 官方的制谱器其实不是在这个界面下进行编辑的
2. 粒子特效可以按`O`进行关闭，关于快捷键见第6条
3. 节拍分组与拍线的设计皆沿自 osu!lazer 的编辑器与原版 Dynamaker，关于拍线的显示我暂时没有更好的想法，问题可能出在三侧编辑的方式，其余见第5条
4. 很特别的建议，但我其实不太明白此功能对“更方便看到判定时间”有什么样的意义，出于还原Dynamix动画的考虑在得到进一步的解释之前我可能不会添加这个特性
5. 节拍线在判定线前... 我不太理解这一条的含义，是指在判定线的底部再添加一定的编辑空间吗？编辑器的界面主要沿自 Dynamaker，改进这点需要全新的编辑模式，或许之后会添加
6. 主要使用快捷键的原因是因为
  * 我个人在使用 Dynamaker 的时候一直都是快捷键操作，没有注意到右键菜单与可视化选项的重要性
  * 在 Gamemaker 下实现美观的 UI 需要时间...

这是对以上问题的解答，如果需要针对各个功能提出具体建议可以分条提交issue并更加详细地阐释你想要的效果（至少能让我理解为什么需要这么做）

如果之后有系列的建议或者问答可以移步 Discussion 进行讨论

**Comment by iam6668** [comment]
那这边需要我删掉这条并分开进行解释吗?详细情况是否需要联系说一下

**Comment by NagaseIori** [comment]
> 那这边需要我删掉这条并分开进行解释吗?详细情况是否需要联系说一下

如果你觉得该 issue 不再需要进一步讨论则可以使用 Close issue 来关闭该 issue。

关于你说的这 6 点我基本上分别进行了解释，如果你觉得某些功能仍然有必要进行进一步讨论则可以分别提交 issue 单独展开讨论。

**Comment by iam6668** [comment]
不好意思，没有看到指南上面的5个选项
