### ISSUE TITLE
特殊的节奏拍号功能

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#62]
支持特殊的节奏拍号，对于任意1/x拍号，x可以选为任意数字（当然要设个上限，个人认为50最好），当然因为大部分歌曲还是常规的拍号，所以现在这个拍号选择方案也可保留，这个功能建议是想用来支持更多非常规拍号的歌曲（比如LeaF的彁，还有arcaea的testify等，有各种刁难的5分音，22分，32分）

**Comment by NagaseIori** [comment]
32分属于 1/2 类别
1/5 属于第 B 组
1/11 、1/13、1/15 可以考虑添加到第C组
任意数字不好添加，因为不好设置颜色，不过倒是可以添加一个查找切换功能...

**Comment by iam6668** [comment]
这个查找切换功能是？

**Comment by NagaseIori** [comment]
> 这个查找切换功能是？

输入数字就可以直接切换到对应的节拍细分，不需要再使用Q、E与G键来调整节拍分组

任意的细分数字我想应该可以支持，如果统一颜色的话

**Comment by iam6668** [comment]
那就好，这里再提一下，对于非质数非常规拍号，可以选择分解质因数进行显示
比如22分中可以拆成2*11，那么在显示的时候可以先对2分进行显示红色，剩下的11分如你所说根据下落速度或一定的密度判别式决定隐藏节拍线与否
这里再提一嘴，比如24分音，3*2^3,建议优先级给2^3，因为很显然2分音比3分音更常见
