### ISSUE TITLE
音符属性请求添加

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#63]
（灵感来自re：phiedit）
求添加拍号属性，如对于第33小节第3个五分音的note表示为`（33）3/5`
对于任意拍子的第2个四分音`(x)2/4`由于可以简化为`(x)1/2`，因此可以给使用者是否简化的选项，不能简化时（比如2分拍时有四分音符）则保留，配合时间吸附功能，方便采音

**Comment by NagaseIori** [comment]
这个功能在 Dynamaker 中也存在，如果要加入 #62 这个功能会是必要的。

**Comment by NagaseIori** [comment]
done https://github.com/NagaseIori/DyNode/commit/275d094b3bb4b0897316948b8baecee421e746d5
