### ISSUE TITLE
设置或工具栏功能添加

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#64]
如标题，随着功能增加，单一功能的多种编辑方式将意味着快捷键只能选择所有功能的其中一种常用编辑方式（当然不是绝对的），即使功能对应的编辑模式只有一个，大家也需要通过查阅文档的方式去学习，虽然说编辑器本身肯定要学的，但添加设置或工具栏这种可视化操作方便他人学习，当然也就方便操作了（毕竟不是所有人都用过，比如我开始就是拿dynode进行dynamix谱面制作）
由于目前2.0任务进度较多，目前该建议可试行方案是添加设置功能，在设置功能里对任一功能的多种编辑方式用列表的方式（即编写这个功能时用字典或列表，编辑器中默认为折叠状态）进行陈列，哪怕功能少因为有了对应功能描述和选项，这一切也一目了然，而且这样后面还能相对好维护一些，除非能确保该功能是二元的且无法量化，不然不建议用bool值进行选择
当然，有余力可以弄两级甚至更多级设置，这样也方便添加署名，版本号之类的，大家也能从文件本身就看出目前编辑器的情况，顺带着可以的话也避免了版权纠纷之类的麻烦

**Comment by NagaseIori** [comment]
0.2.0 的预定计划就是添加一定的可交互式界面，如果有这种界面那么设置会是最先被添加的部分。
0.2.0 的计划见 #7 。
