### ISSUE TITLE
正侧面音符设置宽度分离与优化

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#67]
在写谱的时候我们经常需要写侧边音符**视觉长度**上与正面音符相等的note，但因为宽高比不可能是1：1，所以实际上正面的1长度的note与侧面的1长度note视觉上长度差的比较大
所以方便起见，想着可不可以有两种模式，一个是**视觉**等长，一个是数值等长，或者说设置里自定义一个数值，在切换侧面时未放置note的长度是正面note长度乘以那个自定义数值，这样以后放置的时候对于一些配置不需要频繁切换

**Comment by NagaseIori** [comment]
这个问题我很早就考虑过，预计之后也会加入类似的解决方案
