### ISSUE TITLE
编辑模式增加（超前开发计划）

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#68]
现有的编辑模式依旧像dynamaker一样不是很方便，例如在正常降落速度下观看的谱面内容量较小，频繁切换正面侧面带来的不必要的工作量增加等
对此本人参考了其他游戏的非官方制谱器，个人认为可以仿照出一个不错的编辑方案，便是三个面分为三个部分进行编辑，要写侧面的时候换界面就好，剩下的可以照常，具体方案如图（不好轻喷QAQ）
![新编辑模式草图](https://user-images.githubusercontent.com/68184937/198980317-45734562-4986-4562-9510-bfa124c64671.png)
仅供参考，不合适可以关闭

**Comment by NagaseIori** [comment]
参考的是 Deenote ？其实我与 Jmak 讨论过后可能更倾向于做 Cylheim 感觉的布局。

UI 计划、布局与新的编辑模式都已在计划中，见 #7 

但总之很感谢你的大量建议w

**Comment by iam6668** [comment]
这个其实是看re:phiedit和cylheim想出的办法，其实我想表达的就是把三个面分开写就好，然后我看2.0计划没有啊？？？可能是我理解错了吧，或是有些专业名词不理解
最后不用客气，能有这么方便又人性化的制谱器并使用是我的荣幸，既然我也玩过一点编程，我也大概知道GitHub咋玩，提出我的建议是我的一点心意，我看到的你没计划的都会说的
