### ISSUE TITLE
双hold首判重合优先级显示问题

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#70]
![音符优先级](https://user-images.githubusercontent.com/68184937/199157693-e088d810-030b-469b-bf66-6b25ccbae62c.png)
如图所示，按理来讲下面的音符应该和上面音符一样比背景hold音符优先展示，但不管背景hold与下面hold的放置顺序都会有这个问题，望调查并改正

**Comment by iam6668** [comment]
补充，在反复调整时间线时偶尔会优先显示（不过目前只有一次）

**Comment by NagaseIori** [comment]
已复现
