### ISSUE TITLE
变bpm的xml导入出错

### ISSUE THREAD

**Issue by iam6668** [NagaseIori/DyNode#74]
![F}~ C(@JL}6REWC{W{%%H~K](https://user-images.githubusercontent.com/68184937/199866919-0032c676-6ec3-4778-ae04-b4418e5b8acb.png)
![VF$@3K%4JNDGS4KU_{KT$K9](https://user-images.githubusercontent.com/68184937/199866920-5390ce22-3f57-4769-ba95-f7252083f841.png)
如图，经过反复试验一直如此

**Comment by iam6668** [comment]
由于与#52重复，这里给出谱面文件

**Comment by NagaseIori** [comment]
你使用的XML文件存在基本的格式问题。

这是你导出的 Dynamaker-modifed 的 XML 谱面文件：
![屏幕截图_20221104_104909](https://user-images.githubusercontent.com/31349569/199874588-de70bb4a-c6f0-48fe-8bb9-a0a5691880a0.png)

这是使用 Dynamaker-modifed 1.21.4.1 导出的 XML 谱面文件：
![屏幕截图_20221104_104923](https://user-images.githubusercontent.com/31349569/199874684-cdeac082-adf8-43a6-b6a7-689031d1400d.png)


我们建议你使用最新版本的 Dynamaker-modified 来导出变 BPM 数据或使用 Save for dynamite 以避免不必要的错误。

同时，我们不推荐你使用来自 Dynamaker-modified 中的变 BPM 数据。详见 [此页面](https://dyn.iorinn.moe/guide/import.html) 。

**Comment by NagaseIori** [comment]
Jmak 本人确认 Dynamaker-modifed 的确会导出这种格式的谱面，感谢反馈，待修复

**Comment by NagaseIori** [comment]
@all-contributors
please add @iam6668 for giving ideas, feedback, testing and bug reports
please add @jmakxd for ideas, original designer and feedback

**Comment by jmakxd** [comment]
Changing BPM is easier in DyNode than DynaMaker, DynaMaker's BPM change function is really buggy and we still couldn't figure out a way to improve it. But if you know what you are doing and can ignore the BPM lines while charting a BPM change chart, go ahead and use DynaMaker. DyNode is currently preferred for BPM change function.
